### ISSUE TITLE
Explicit license

### ISSUE THREAD

**Issue by smipi1** [tux-mind/libbthread#2]
Hi,

Could you please explicitly choose an open-source software license for libthread? I would really like to use your library, but legal will not allow it until the license is explicit.

Most of the sources are LGPLv2, so I would recommend doing so for the package as a whole. Just adding the LGPLv2 text to a file called LICENSE would be sufficient.

Thank you,
Pieter Smith

**Comment by esminis** [comment]
Any news on license?

**Comment by oxr463** [comment]
@tux-mind would you consider a PR for this?

**Comment by tux-mind** [comment]
Done :)

**Comment by smipi1** [comment]
Thanks!
