### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by Jolt151** [tux-mind/libbthread#3]
I'm trying to build this library (using termux) so I can build ettercap. How do I build it so I can include it in the ettercap source?

**Comment by Cvar1984** [comment]
> I'm trying to build this library (using termux) so I can build ettercap. How do I build it so I can include it in the ettercap source?

https://stackoverflow.com/questions/2531827/what-are-makefile-am-and-makefile-in

**Comment by tux-mind** [comment]
Readme updated :)
