### ISSUE TITLE
Help wanted unofficial

### ISSUE THREAD

**Issue by Saikatsaha1996** [tux-mind/libbthread#7]
Please don't ignore 🙏
I want to install sgminer in termux
But I got this types of error
Please help me how can I slove🙏
![Screenshot_2021-05-20-00-55-16-423_com termux](https://user-images.githubusercontent.com/72664192/121811904-850dfa80-cc83-11eb-9988-32e90f042daa.jpg)

**Comment by gendy-98** [comment]
@Saikatsaha1996 
Hi,
Did you solve your problem?

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 Hi, Did you solve your problem?

Sorry. Sir actually android doesn't support lpthread cancel program.. that's why I can't solve it.. 

Actually I don't know about c++ codes
Thank you ☺️

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 Hi, Did you solve your problem?

Can you please share any solution

**Comment by Saikatsaha1996** [comment]
Getting error 
![Screenshot_2021-12-10-21-27-20-778_com termux](https://user-images.githubusercontent.com/72664192/145603246-d4a2aec1-2656-4daf-8575-23f9b48208b6.jpg)

**Comment by gendy-98** [comment]
> 

sorry but I couldn't find any solution

**Comment by gendy-98** [comment]
regarding the screenshot go to your compiler bin directory were you can find aarch64-linux-android-clang you may find that ar has another name make a symlink with aarch64-linux-android-ar it may solve ur problem

**Comment by Saikatsaha1996** [comment]
> regarding the screenshot go to your compiler bin directory were you can find aarch64-linux-android-clang you may find that ar has another name make a symlink with aarch64-linux-android-ar it may solve ur problem

Reinstalled Solved ..

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 Hi, Did you solve your problem?

Can you try for me  sgminer-arm ?
I just want to kno why I can't install it

**Comment by Saikatsaha1996** [comment]
> regarding the screenshot go to your compiler bin directory were you can find aarch64-linux-android-clang you may find that ar has another name make a symlink with aarch64-linux-android-ar it may solve ur problem

can you help me please ? Now pthread cancel working but i don't know why I am getting this error..


Please help me please don't ignore..

![IMG_20220121_124757](https://user-images.githubusercontent.com/72664192/150483428-2b57c7df-3e8b-4a77-b291-ffa6c38e0cd4.jpg)

**Comment by gendy-98** [comment]
Sure I will help 
Can you first tell me what you did to try avoiding the issue

**Comment by Saikatsaha1996** [comment]
> Sure I will help Can you first tell me what you did to try avoiding the issue

just Compile with android ndk clang api 28..
Than i install it.. 

After that i same ..
https://github.com/JordanRulz/cgminer.git

I want to compile this one..

**Comment by Saikatsaha1996** [comment]
I installed libbthread 

~/libbthread $ autoreconf -i                                                libtoolize: putting auxiliary files in '.'.                                 libtoolize: copying file './ltmain.sh'                                      libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,   libtoolize: and rerunning libtoolize and aclocal.                           libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.      configure.ac:25: installing './compile'                                     configure.ac:25: installing './config.guess'                                configure.ac:25: installing './config.sub'                                  configure.ac:23: installing './install-sh'                                  configure.ac:23: installing './missing'                                     Makefile.am: installing './depcomp'                                         ~/libbthread $ export PATH="$PATH:$HOME/toolchains/android-ndk-r23b/toolchains/llvm/prebuilt/linux-aarch64/bin"                                         ~/libbthread $ target_host=aarch64-linux-android                            export AR=${target_host}-ar                                                 export AS=${target_host}-as                                                 export CC=${target_host}24-clang                                            export CXX=${target_host}24-clang++                                         export LD=${target_host}-ld                                                 export STRIP=${target_host}-strip                                           export CFLAGS="-fPIE -fPIC"                                                 export LDFLAGS="-pie"                                                       ~/libbthread $ ./configure --host=${target_host} --prefix=$PREFIX
make
make install

**Comment by Saikatsaha1996** [comment]
> > 
> 
> sorry but I couldn't find any solution

@gendy-98 @tux-mind 

After including bthread.h file my pthread-cancel problem solved but getting last error..

Can you give me solution please ?

![Screenshot_2022-05-07-00-37-00-840_com termux](https://user-images.githubusercontent.com/72664192/167202857-53980243-6df4-4695-97b4-c1507673b5fc.jpg)

**Comment by Saikatsaha1996** [comment]
> Sure I will help Can you first tell me what you did to try avoiding the issue

Pthread-cancel problem solved finally..
I just #include bthread.h in this code
And under bthread.h #include pthread.h

Pthread-cancel problem solved..

Thank you for your code.. and also some one helping me ..

**Comment by Saikatsaha1996** [comment]
Undefined reference to pthread-cancel
![Screenshot_2022-05-24-03-18-42-315_com termux](https://user-images.githubusercontent.com/72664192/169913820-26921cf6-bf40-4ede-8f25-6cca78e0d7ba.jpg)

**Comment by Saikatsaha1996** [comment]
@tux-mind can't find solutions for undefined reference to `pthread_setcancelstate

Solution please @tux-mind 
![Screenshot_2022-05-24-22-43-05-565_com termux](https://user-images.githubusercontent.com/72664192/170094137-5dd2df03-6c2a-4970-a4eb-2fd45c3088f5.jpg)

**Comment by Saikatsaha1996** [comment]
@gendy-98 @tux-mind  @n3vermind  @esminis 

Dear Sir/Madam

Ultimately i found actual problem ..
'''
pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);

pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, NULL);


pthread_testcancel();

pthread_cancel 

'''

not working with bthread.h

pthread_cancel program works with athread.h



#include <pthread.h>
#include <signal.h>

#define SIG_CANCEL_SIGNAL SIGUSR1
#define PTHREAD_CANCEL_ENABLE 1
#define PTHREAD_CANCEL_DISABLE 0


static int pthread_setcancelstate(int state, int *oldstate) {
    sigset_t   new, old;
    int ret;
    sigemptyset (&new);
    sigaddset (&new, SIG_CANCEL_SIGNAL);

    ret = pthread_sigmask(state == PTHREAD_CANCEL_ENABLE ? SIG_BLOCK : SIG_UNBLOCK, &new , &old);
    if(oldstate != NULL)
    {
        *oldstate =sigismember(&old,SIG_CANCEL_SIGNAL) == 0 ? PTHREAD_CANCEL_DISABLE : PTHREAD_CANCEL_ENABLE;
    }
    return ret;
}


static inline int pthread_cancel(pthread_t thread) {

    pthread_kill(thread, SIG_CANCEL_SIGNAL);
}





Every time getting error with 


undefined reference to pthread_setcancelstate

undefined reference to pthread_testcancel

undefined reference to pthread_setcanceltype



Can it possible to give me a solution ?

**Comment by Saikatsaha1996** [comment]
My mistake i am a big idiot...🥲
All problem solved with just need to add 
-lbthread 

Thank you ..
Build done without a single error 😊

![Screenshot_2022-05-25-16-09-55-618_com termux](https://user-images.githubusercontent.com/72664192/170244074-f2d60932-bc76-426f-94bf-e60992f42a50.jpg)

**Comment by Saikatsaha1996** [comment]
@tux-mind @gendy-98
pthread_setaffinity_np

Support in in bthread ?
